### ISSUE TITLE
"plugin.video.abelhas" Add to Library (Movie) /  B COLOR go

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#10]
When "Add to Library (Movie)" a file with the name:
I,.Frankenstein.2014.1080p.BluRay.x264.YIFY.mp4

It will create a folder: " B COLOR go"
And a strm file: "+B+COLOR+go"

Cheers!

**Comment by Mafarricos** [comment]
plugin.video.abelhas-1.0.3~beta002 should fix that.
