### ISSUE TITLE
"plugin.video.abelhas" Soap Opera Numbering Exception

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#11]
Example:
Jardins.Proibidos.Ep197.TVRip.XviD.avi
or
Jardins.Proibidos.E197.TVRip.XviD.avi

Could rename the file to:
Jardins.Proibidos.S01E197.TVRip.XviD.avi
But can it handle 3 digit episode?

**Comment by Mafarricos** [comment]
Is episode 197 from season 1 or episode 97 from season 1?
Even so I dont think the scrapper from seasons will recognize Jardins Proibidos as a tvshow.

**Comment by jorgeavlobo** [comment]
Usually there are no seasons in soap operas, they are just numbered.
Soap operas can usually have more than 100 episodes.
The previous example I gave is episode 197.
Cheers!

**Comment by Mafarricos** [comment]
plugin.video.abelhas-1.0.3~beta003 should accept format Jardins.Proibidos.Ep197.TVRip.XviD.avi

And convert it to folder: Jardins Proibidos, subfolder S01 and then episodes there.

This works for you?
Scrapper will not identify the episodes, has is a Portuguese Soap and not a TV Show

**Comment by jorgeavlobo** [comment]
Yes, it will work! Thanks!
Once again, these are just small details, the addon is already really nice.

**Comment by jorgeavlobo** [comment]
Tested and working!
