### ISSUE TITLE
"plugin.video.abelhas" Add to Library (TVSHOW) - Batch / 29 files limitation, maybe not bug

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#12]
When "Add to Library (TVSHOW) - Batch", it can only add 29 files to the library, even if the main folder has more than 29 files.

Did not test this on "Add to Library (MOVIE) - Batch", but it should be the same.

Do not know if this is limitation of the website "Abelhas.pt" itself or if it can be worked around/tweaked.

Thanks!

**Comment by Mafarricos** [comment]
Can you show me and abelhas folder were that happens?

**Comment by jorgeavlobo** [comment]
It happens in every folder that has more than 29 files inside.
If you realize, when you navigate inside de Abelhas Add-on in Kodi, the folders only display 29 files, if you want to see more you need to press "Go to next page".

**Comment by jorgeavlobo** [comment]
That's why I think it only adds what it "sees", not everything that's inside the main folder.

**Comment by Mafarricos** [comment]
It works like abelhas site, the addon only sees what abelhas site show, and you only have 30 files each time.

It should display 30, if displays 29 I will check why isn't displaying the last or first.
But about all it will not display, you have to go to second page and add those ones.

**Comment by jorgeavlobo** [comment]
Maybe it is displaying 30 for sure, it has an episode 00 and goes up to 29.
If it is limitation you can tag this topic and close it.

Obrigado!
