### ISSUE TITLE
"plugin.video.abelhas" Script Error

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#13]
Had a script error in two different files but it still played.
Dunno why.

Log file in attachment:
https://www.dropbox.com/s/ic5mihj3zynf967/kodi.log?dl=0

**Comment by Mafarricos** [comment]
Did you activated subtitles on abelhas addon and didn't choose the languages?
And did you activated the languages here:
![image](https://cloud.githubusercontent.com/assets/2441379/8086171/e18689dc-0f8b-11e5-8ab0-761b4faba08c.png)

"Transferir Legendas para estes idiomas".

I think is a problem related with that.

**Comment by jorgeavlobo** [comment]
Subtitles are activated in both places for French subtitles.
Maybe the problem is because it does not find subtitles?

**Comment by Mafarricos** [comment]
You allways get the same error in the same video?

**Comment by jorgeavlobo** [comment]
I will test it in a few days, don't bother with this. It is a perfectionism.
Cheers and thanks!

**Comment by Mafarricos** [comment]
plugin.video.abelhas-1.0.3~beta004 should control exception errors while searching subtitles
