### ISSUE TITLE
"plugin.video.abelhas" Add to Library (Movie) - Batch / Folder Creation With Special Characters

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#14]
When "Add to Library (Movie) - Batch" if a filename is: À Procura de Nemo.avi
It will create a folder \xc31x80 Procura de Nemo

Similar thing happens with teh caracter: õ

**Comment by Mafarricos** [comment]
I will check how to replace portuguese characteres to the ones without the "~´`" etc.
but that way adding portuguese names you don't get the movie information, as in the scrapper it's in english.

**Comment by jorgeavlobo** [comment]
It in english but I think it fetches names also with special characters, shall we try it?
Even if it doesn't fetch, it sure doesn't fetch with a name starting with "\xc31x80" :)

File name:
À.Procura.de.Nemo_[BDRip.1080p][PT-PT.ENG].mkv

This file will create a strange folder name.

**Comment by Mafarricos** [comment]
À.Procura.de.Nemo_[BDRip.1080p][PT-PT.ENG].mkv

You should create as Finding Nemo, and that you will not have a problem.

**Comment by jorgeavlobo** [comment]
It won't, but the default folder that it prompts you to create starts with "\xc31x80"

**Comment by Mafarricos** [comment]
Yes, but you should not use portuguese names, if you want integration with scrapper.

**Comment by jorgeavlobo** [comment]
Poxa, vou-me chatear com os Rippers que andam a dar nomes tugas aos ficheiros ;)

Fast workaround: I rename!

**Comment by Mafarricos** [comment]
Already changed code so special chars are replaced with normal chars.
Will be released in next beta.
