### ISSUE TITLE
"plugin.video.abelhas" Movie/TVSHOW Library Integration Folder / Cannot use FTP location

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#15]
Somehow, Abelhas cannot save the strm files into an FTP.

Here goes the log file:
https://www.dropbox.com/s/x6utd8iz8lsnnvh/kodi-ftp.log?dl=0

Thanks!

**Comment by Mafarricos** [comment]
Can you check if Genesis can save strm files to FTP?
I use the same code.

**Comment by jorgeavlobo** [comment]
Cannot test stuff now, my desktop stayed behind for a few days of holidays.
Sorry.

**Comment by Mafarricos** [comment]
@jorgeavlobo did you already tested if Genesis can save to ftp?
Probably this isn't a feature that can be done.

**Comment by jorgeavlobo** [comment]
Still haven't sorry.
Will do it on Thursday or Friday.

**Comment by jorgeavlobo** [comment]
@Mafarricos Genesis cannot save to FTP either.
Just checked it.

**Comment by Mafarricos** [comment]
Probably a kodi problem. I will investigate if there is another way of saving it, but probably not.

**Comment by jorgeavlobo** [comment]
Thanks for trying and for the time you spend on the whole Abelhas addon project.

**Comment by Mafarricos** [comment]
for what I'm seeing the problem isn't saving the file, is creating folders on ftp...

**Comment by Mafarricos** [comment]
beta014 should fix this.
ftp port must be 21 and no secure ftp, only standard ftp.

@jorgeavlobo check if all works with this.

**Comment by jorgeavlobo** [comment]
Whow... It works!!!
Great job!

In what language is Abelhas addon written?

**Comment by Mafarricos** [comment]
python as almost all kodi addons.

**Comment by Mafarricos** [comment]
Already applying this new code to genesis, let's see if lambda approves ;)
Next will be my addons resolver :)

**Comment by jorgeavlobo** [comment]
Keep up the good work!!!

Cheers!
