### ISSUE TITLE
"plugin.video.abelhas" Play Trailer from Library Script Error

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#17]
Kodi main screen > Movies > Right Click on a Movie > Movie Information > Trailer

"Playback failed, couldn't locate video url"

Cheers!

**Comment by Mafarricos** [comment]
Anything that is from library isn't a abelhas addon problem.
Just tested and worked with me.
Probably you didn't setup the scrapper to get trailer url's.
