### ISSUE TITLE
"plugin.video.abelhas v1.0.3~beta005" Add to Library (TVShow) no longer working

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#18]
Both "Add to Library (TVShow)" and "Add to Library (TVShow) - Batch" are not working anymore on this beta, script failed error.
The "Add to Library (Movie)" and "Add to Library (Movie) - Batch" still work normally.
![add to](https://cloud.githubusercontent.com/assets/12179834/8120977/32ab8d8c-109d-11e5-96f8-2d422862befa.png)
![error](https://cloud.githubusercontent.com/assets/12179834/8120979/352122d4-109d-11e5-9832-41d14369d6d9.png)

Cheers!

**Comment by Mafarricos** [comment]
plugin.video.abelhas v1.0.3~beta006 fixes this

**Comment by jorgeavlobo** [comment]
Obrigado!
