### ISSUE TITLE
"plugin.video.abelhas" Add to Library - Folder Name with ":"

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#19]
After adding a file to library and it prompts you to choose a folder name, if you write something with ":", for example:
Ice Age: Continental Drift (2012)

The addon won't add the file to the library (aka create a folder) nor give you an error telling you that you cannot choose that folder name.

This bug might make you not adding a few movies to your collection if you're adding a file with the batch option and you don't realize it.

Cheers!

**Comment by Mafarricos** [comment]
beta007 should fix that. Special chars like that will be changed to space.

**Comment by jorgeavlobo** [comment]
Many thanks!
