### ISSUE TITLE
Feature  request to allow centralised tracking folder.

### ISSUE THREAD

**Issue by gb160** [Mafarricos/Mafarricos-xbmc-dev-addons#23]
Hi, is it possible to give the user the choice of where the tracking folder  is located?
This would mean that my resume points would be available to all my different clients, meaning I could start watching a movie downstairs , then resume watching it from my bedroom.
Obviously each client would need to be set to look in the same location.

Obviously the default location would be where it  currently is,
Personally I would have it on my samba share where all my local media is stored.

thoughts?

**Comment by Mafarricos** [comment]
beta011 should work like that.

![image](https://cloud.githubusercontent.com/assets/2441379/8271841/f0d49f0a-1823-11e5-8bf9-712137c01324.png)

**Comment by gb160** [comment]
Great Progress already !!!

Problem though...
Ive set the Resume folder on my samba share, the individual files are being created when i start playback, but if i stop playback, they're not being picked up when i try to resume....the playback starts from the beginning again, and the time in the individual file just starts over again from 0.
I never get the yes no dialog to resume, although i notice in the log it says "Resume point available..."

Full log here...
http://pastebin.com/aWEf1WJs 
This feature can come in very useful, thanx !!

**Comment by Mafarricos** [comment]
Do you have admin permissions on smb login?

I see the errors:
15:20:57 T:4616290304 WARNING: Close: failed to delete temporary file ""
15:21:01 T:4601229312 WARNING: Previous line repeats 1 times.
15:21:01 T:4601229312 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://RASPBIAN/Raspbian%20SD%20Card/Albehas%20Resumes/The%20Goldbergs%202013%20S02E18.txt
15:21:01 T:4599017472  NOTICE: -->Python Interpreter Initialized<--
15:21:06 T:4601229312 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://RASPBIAN/Raspbian%20SD%20Card/Albehas%20Resumes/The%20Goldbergs%202013%20S02E18.txt

It seems that the file can't be overwriten and also can't be deleted.
I don't know if this is a code error or permission error.

**Comment by gb160** [comment]
I can create and delete files as a guest in samba with no username or password....also if it was a permissions problem would it create the files in the first place?

This line ..." WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - " appears very regularly in my log whenever samba read/write is occurring.

Shame as this feature could be very useful.

**Comment by Mafarricos** [comment]
If you search that error on google it states sometimes problems related to permissions. Will check for more details.

**Comment by gb160** [comment]
There was a similar issue a while back with writing .strm files to my samba share...in the end I think you copied the code from genesis and it solved the issue.

**Comment by Mafarricos** [comment]
The code is the same. Probably is related with rewrite permissions. Will have to check how to reproduce the same problem to fix it ;)

**Comment by Mafarricos** [comment]
Check beta013.

It saved my on smb running on android and also ftp on internet.

If you still have problems is something to do with permissions on your smb share.

**Comment by gb160** [comment]
Well done...I'll test this again tonight, at least now if I have problems it must be my system, thanks for testing.

**Comment by gb160** [comment]
I can confirm that beta013 fixes my resume problem....i didn't need to change anything on my samba setup.

Is it safe to fork this now? You don't plan on updating anything in the next few hours?

**Comment by Mafarricos** [comment]
You don't need to fork, only to create a PR of my changes on your fork. But if is easier you can fork it again.
I will not work on the addon. Right now no bug reported ;)

**Comment by gb160** [comment]
new PR issued....im waiting for u to tell me whats wrong with it !

**Comment by Mafarricos** [comment]
Will check it at night ;)
