### ISSUE TITLE
"plugin.video.abelhas" Add to Library (Movie) / Folder Name with "/"

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#24]
After adding to library and choosing folder name "50/50 (2011)" it won't create the folder.

Request to create the folder: "50-50 (2011)" or even "50 50 (2011)".

Thanks in advance!

**Comment by Mafarricos** [comment]
Didn't understood. The / is changed to space or minus?

I think / should be changed to /. That doesn't happens?

**Comment by jorgeavlobo** [comment]
It can be changed to space or minus or fullstop, whatever you decide.
The addon doesn't give you an error if you try to create a folder named "50/50 (2011)".
It will simply not create anything.

Cheers.

**Comment by Mafarricos** [comment]
beta012 should fix this.
