### ISSUE TITLE
"plugin.video.abelhas" Multi-Language Local Subtitles Improvement

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#25]
Is it possible to allow the addon to detect multi language local subtitles?
I know it detects:
Video.avi
Video.srt

Can it detect?
Video.avi
Video.English.srt
Video.Portuguese.srt
Video.French.srt

Kodi supports this already:
http://kodi.wiki/view/Subtitles#Using_multi_language_subtitles

Cheers.

PS:
@Mafarricos and @gb160 thanks for all the recent great updates!

**Comment by Mafarricos** [comment]
The addon it self only detects one subtitle on the same folder. Don't know if will be easy to do that.

**Comment by jorgeavlobo** [comment]
Ok, no problem, but it would be a great improvement.

**Comment by jorgeavlobo** [comment]
Any updates on this?

Abelhas is working flawless, the updates you made, made my home cinema experience perfect!

**Comment by Mafarricos** [comment]
Not thinking in new features, because probably abelhas will not be free to download other people stuff,

**Comment by jorgeavlobo** [comment]
If it maintains free to download our own stuff it will already be a great service.
But I have a feeling that the stuff that we have copied from others in the past and is nowadays inside our private folder, will be counted as other people stuff and counted as traffic.
Let's see...

**Comment by Mafarricos** [comment]
Yes, I also think that.

**Comment by jorgeavlobo** [comment]
Any alternative to Abelhas?
What will be the next gen service?
