### ISSUE TITLE
Albehas Page Error.Try again.

### ISSUE THREAD

**Issue by gb160** [Mafarricos/Mafarricos-xbmc-dev-addons#27]
I'm getting this error, along with playback failed for a lot of stuff.
Can anyone verify is this is an addon problem or  a website problem?

**Comment by Mafarricos** [comment]
When I tested your changes I also got this error sometimes, but thought it was the site.
Probably last changes are giving some kind of problem at first try?

**Comment by Mafarricos** [comment]
Check again with: https://github.com/Mafarricos/Mafarricos-xbmc-dev-addons/blob/master/repo/plugin.video.abelhas/plugin.video.abelhas-1.1.0.014.zip
That was last version prior to your changes, on that one you almost never had the try again error.

The log file doens't clues were can be the error?

**Comment by gb160** [comment]
Cant really try that now mate....but I've just tried on Albehas website and its slow as hell and some pages won't load at all.
I think (hope) the problems at the website end.

**Comment by Mafarricos** [comment]
Probably the url isn't solved on timeout limit and gives that error, or
search for the metadata takes more time?

2015-06-23 14:07 GMT+01:00 gb160 notifications@github.com:

> Cant really try that now mate....but I've just tried on Albehas website
> and its slow as hell and some pages won't load at all.
> I think (hope) the problems at the website end.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mafarricos/Mafarricos-xbmc-dev-addons/issues/27#issuecomment-114494313
> .

## 

Carlos Correia

**Comment by gb160** [comment]
Sorry mate, i meant I've tried in a web browser, i think the websites having issues.

**Comment by Mafarricos** [comment]
Yes, if site is slower probably takes more time on addon and gives timeout ;)
But when I tested your changes I got also sometimes that kind of errors.

**Comment by gb160** [comment]
Thats strange...ive never seen that error once in the hundreds of times i was testing my code.
I hope its coincidence that the issues on the website mustve already started when you were testing last night?

ill leave this issue open until we can verify the cause.

On the website I'm getting 'video not found'

**Comment by Mafarricos** [comment]
If you also get errors on the site, it must be the site.

**Comment by gb160** [comment]
ok, ill close this for now, and reopen later if required.

**Comment by gb160** [comment]
Well the websites almost unusable atm....is it likely to be down for long?

**Comment by jorgeavlobo** [comment]
The site is working nice on my connection.

**Comment by gb160** [comment]
It's terrible here in London....really terrible :( 
Can u test the addon? Are u getting errors?

**Comment by jorgeavlobo** [comment]
I'm unable right now, I'm on my cellphone.

**Comment by Mafarricos** [comment]
Can only test it in 3-4 hours

**Comment by Mafarricos** [comment]
Tested right now, and seems not to be any problem.

**Comment by gb160** [comment]
so if u go to:

http://abelhas.pt/VTx/Series+-+TV+Shows/American.Crime.S01/HDTV

you can play s01e01 with no problems

**Comment by Mafarricos** [comment]
Yes, started without any problem.

**Comment by gb160** [comment]
Is that in kodi?

**Comment by Mafarricos** [comment]
Yes.

**Comment by gb160** [comment]
Weird.....I wonder what the hell is causing this?

**Comment by Mafarricos** [comment]
Try to check logfile.

**Comment by gb160** [comment]
I'm getting script errors now as well.
before it was just a dialog with 'Page Error' 
log:
http://pastebin.com/VK2sceVR

**Comment by Mafarricos** [comment]
if re.search('Por favor, tenta baixar este ficheiro mais tarde.',final):
It seems that variable isn't correct, even so the error is because the file isn't avaiable on abelhas.

**Comment by Mafarricos** [comment]
Hum, the problem is that:
final= net.http_POST(endlogin,form_data=form_d,headers=ref_data).content.encode('latin-1','ignore')

is on a try code, so if response from site isn't return, final don't get started, and then you will get an error on the other part of code.

**Comment by gb160** [comment]
I'm getting the same error when playing straight from the addon, ie not in my library....so the contents. Definitely there.

**Comment by Mafarricos** [comment]
Made a little change on beta017.
final is instanciated and now I made a small loop to try gettting final response.

Check if at least the script errors don't happen.

**Comment by gb160** [comment]
Script errors gone, but now just sits with the dialog "Abelhas Loading..." 
Eventually I get the dialog "page error" or "no internet connection"

**Comment by Mafarricos** [comment]
OK, but I think right now should be a problem related with that. Some problem with abelhas site.

**Comment by gb160** [comment]
But you have no problems playing stuff....I can't play a single thing.
Why it affect me , and not u ? Strange....

**Comment by Mafarricos** [comment]
Check tomorrow ;)

**Comment by gb160** [comment]
Ok mate....sometimes it will start playing... But with the 'playback failed' dialog across the middle of the screen, and playback will stop as soon as I try to dismiss the dialog.

**Comment by Mafarricos** [comment]
Yes I also got that error some times, but right now no.

**Comment by gb160** [comment]
Still completely unusable for me :(
'Page error' mainly, with the occasional 'no internet connection'

Can't understand why I'm the only one experiencing this.

**Comment by Mafarricos** [comment]
Try the addon from fightnight that still doesn't have the all the betas changes and see if the problem persists.

**Comment by jorgeavlobo** [comment]
Only now I was able to test this on Kodi. Last night I was only using the website.
I just tried a 8GB movie on Kodi and it played smoothly.
Beta17

**Comment by gb160** [comment]
I've installed the version from the fight night repo, and I'm getting the same behaviour.

**Comment by gb160** [comment]
further update...if i use my VPN connected to Spanish server(no Portuguese available)...everything plays as expected.

I thought maybe that my ISP had added Abelhas.pt to their 'blacklist"(PirateBay etc)....but the strange thing is i can still access the website through any browser with no vpn, and download directly with no problems.

When a site is blocked by my ISP and i try to access it, i normally get a message stating "this site has been blocked by the high court because of file sharing etc etc"

**Comment by Mafarricos** [comment]
Really Don't know what can be.

**Comment by gb160** [comment]
Me 2...not ideal having to use a VPN but at least it's working now.

**Comment by Mafarricos** [comment]
check abelhas IP, and change on the addon the abelhas.pt address for the ip address and see if you get any change.

**Comment by gb160** [comment]
i tried that and I'm just getting 'no internet connection' ....what is even weirder is that I've just set it back to abelhas.pt , tried it again with no vpn and it 'seems' to be working ok.
Im still no wiser as to what caused/is causing this issue, but as of now it all seems to be working ok.
Nice to know the problem can be solved by a VPN, but fingers crossed it stays working and i won't need to use it.
