### ISSUE TITLE
"plugin.video.abelhas" Unable to access friend's password protected folders

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#28]
Abelhas Addon > Amigos > Choose One Friend with password protected folders > Input Password

Error!
Script Failed.

Observation:
This feature is urgent because of recently copyright reports in Abelhas, most users are password protecting their folders.

**Comment by Mafarricos** [comment]
Can you create a folder with your user protect it with a password and tell me the user and password?
So I can test it?

**Comment by jorgeavlobo** [comment]
User: jorgeavlobo
Folder: Kodi
Password: kodirocks

**Comment by Mafarricos** [comment]
I was able to enter on that folder... it have nothing inside.
Do you have any error when you enter on that folder?

**Comment by jorgeavlobo** [comment]
Since I am the owner of the folder it doesn't ask me for a password.
I just transferred a file there, try entering on the folder using Kodi.

**Comment by Mafarricos** [comment]
Yes but i also use my own password folder and doesn't fails to me, let me check.

**Comment by Mafarricos** [comment]
It opens your folder, and file inside.

Could be the password, does the one you are trying have special characters?

**Comment by jorgeavlobo** [comment]
Just sent you and email with the user and password.
Add the user to your friends and then try to go through abelhas addon.
Amigos > User > Insert Password

Cheers!

**Comment by Mafarricos** [comment]
already got the error. I think the problem is that the main user folder (or profile itself) have password.
If you move all files to a folder and got that folder with a password should work.
Almost 100% certain that the addon isn't prepared to request password when you open the user itself.

**Comment by jorgeavlobo** [comment]
Most probably that's the problem.

The thing is that I cannot mess with other people's folder organization.
