### ISSUE TITLE
"plugin.video.abelhas" Add to Library (Movie/TV Series) / Cancel Action

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#4]
In Abelhas, when you > right click on a movie > Add to Library (Movie/TV Series) and now if you have a second thought and decide to cancel the "Create Folder" window, by either hitting the "X" or pressing ESC on the keyboard, you will get a Script Failed! message.

**Comment by Mafarricos** [comment]
Should be fixed in 1.0.2i version.
