### ISSUE TITLE
"plugin.video.abelhas" Add to Library / Auto Update

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#5]
Only now I am testing it! Whow, my movie collection seems nice and tidy!!!
Can you add one nice feature please?
After you "Add to Library" in Abelhas, can you implement for Kodi to update the Library?
AKA, do the following steps:
Kodi > Videos > Files > Right Click on Movies/TV Series Folder > Scan for new content

That way we only need to setup the Movies Master Folder in Kodi and add one file at a time in Abelhas.

**Comment by Mafarricos** [comment]
Should be fixed in 1.0.2i version.

**Comment by jorgeavlobo** [comment]
Be aware, it will only update the library automatically if the video source is already added in Kodi, prior this works you must have setup Kodi this way:
Kodi Home Screen > Videos > Files > Add Videos... > Browse to the same Movie source as in Abelhas Configuration and press OK
