### ISSUE TITLE
"plugin.video.abelhas" Remove from Library Improvement

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#7]
In Abelhas, if the file is already added to the Library (Add to Library (Movie/TV Series)), do you think it might be useful to have a "Remove from Library" feature?
It should also remove from the Kodi Library at the same time.

Maybe common users won't be able remove the old folder manually if they want it.

**Comment by Mafarricos** [comment]
If you want to remove it you only need to go to the Movies folder and remove it.
After adding to library the manage must be done in kodi, not in the addon.

**Comment by jorgeavlobo** [comment]
Going to Movies Folder and deleting them manually doesn't work in some files.

(They have been removed from the Kodi Library but they must be still in use by something, I dunno).

Print screen:
https://www.dropbox.com/s/3txx5fecofvu9pv/Deleting.png?dl=0

**Comment by Mafarricos** [comment]
You can create the folder with the name that you want, how abelhas addon know what to folder delete?
After file is created the managing must be done on kodi side, not on addon side.

**Comment by jorgeavlobo** [comment]
- First point, you're right!
- Second point, I cannot manually delete the folders, Abelhas created them but now I want to delete them and I cannot, even though they are no longer in use by Kodi and I've restarted the computer several times. Maybe this is a Kodi issue, don't bother on this.

**Comment by Mafarricos** [comment]
![image](https://cloud.githubusercontent.com/assets/2441379/8086011/2897dd2c-0f8b-11e5-9b2a-9c3c3163ae6a.png)
Probably you need to activate the delete and rename folder option on kodi.
