### ISSUE TITLE
"plugin.video.abelhas" Movie/TV Show Library Integration Folder Extra Saving Paths Improvement

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#8]
Definições do Abelhas > Configurações Gerais > Movie Library Integration Folder
Can we have more saving paths options?
I wanted to add an FTP server so that I save my *.strm files there.

It is possible in Kodi to add files to the library from FTP servers for example:
Kodi Main Screen > Videos > Files > Add Videos... > Browse > Add network location... > Protocol: FTP Server

Since I have several devices with Kodi installed (Android, Windows and OSX) it would simplify the configuration of each device!

Thanks!

**Comment by Mafarricos** [comment]
Go to System -> File Manager and add your FTP Source.
Then on abelhas settings you open the folder, click 5 times back so you see c:\, etc and there you should see the ftp folder.
This isn't a abelhas addon related problem ;)

**Comment by jorgeavlobo** [comment]
"Then on abelhas settings you open the folder, click 5 times back so you see c:\, etc and there you should see the ftp folder."

You cannot go back 5 times, at least it is not user friendly. If you realize there is no visual display arrow to go back 5 times, you cannot do it with the mouse, but... If you press the backspace button on the keyboard you can go back 5 times!

**Comment by jorgeavlobo** [comment]
I added my FTP source like you mentioned and I configured Abelhas Add-on to save the .strm files to "public_html/MOVIE" and "public_html/TVSHOW".

I added in Kodi the folowing video sources:
"www.example.pt/Movie" for Movies
"www.example.pt/TVSHOW" for Series
(this way to read it won't have to go through authentication like the FTP)

Now I cannot test it because my free FTP host is always down.

Do you think it might work?
Do you think this a good easy workaround for backing up strm files?

**Comment by jorgeavlobo** [comment]
It did not work.
Somehow, Abelhas cannot save the strm files into an FTP.

Here goes the log file:
https://www.dropbox.com/s/x6utd8iz8lsnnvh/kodi-ftp.log?dl=0

**Comment by jorgeavlobo** [comment]
Uploaded the folder manually to the FTP.

The scrapper did not work if Kodi Library had the Movie source pointing to the http source.
The scrapper WORKED if the Kodi Library had the Movie source pointing to the FTP server path.

The scraper fetched the Movies from the FTP!

Now it would be awesome for Abelhas to save the strm files on an FTP.

**Comment by Mafarricos** [comment]
Please check if Genesis can save to FTP.
