### ISSUE TITLE
"plugin.video.abelhas" Add to Library (Animations) Improvement

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#9]
Abelhas already has implemented the features:
Add to Library (Movies)
Add to Library (TV Shows)

Would it be asking too much for the feature:
Add to Library (Animations)

The kids over here would love to see this working!!!

Cheers!!

**Comment by Mafarricos** [comment]
Kodi can't identify animations. Only movies, tvshows, music and concerts.
So isn't possible to do that.
Animations are always a movie or a tvshow ;)
